### PR TITLE
Update API documentation

### PR DESCRIPTION
**Pull request by JayamalHettiarachchi**
Added api/v2 documentation

### CODE REVIEW

**Review by dinesh-amarasekara — CHANGES_REQUESTED** [review]
So as discussed please add an example for `/api/v2`. We better mention what is the different between v1 and v2 and what is the purpose of adding `v2`? etc. The code example can be added to location `examples/api/v2/job` perhaps.

**Review by benhauser — COMMENTED** [review]
Any chance we can make the `ids` parameter optional? If not specified we default to the latest IDS version (currently 2024).

**Comment by JayamalHettiarachchi** [comment]
> Any chance we can make the `ids` parameter optional? If not specified we default to the latest IDS version (currently 2024).

Hi @benhauser,
It is not a mandatory parameter. I made it optional. And if it is not specified it will use the latest version. Sorry for the confusion, I'll update the readme file. 

Thanks,
Shanuka

**Comment by JayamalHettiarachchi** [comment]
Hi @benhauser,
I've updated the API documentation. 

Thanks,
Shanuka

**Review by benhauser — APPROVED** [review]

**Review by dinesh-amarasekara — APPROVED** [review]

**Pull request merged**
